# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('published', models.DateTimeField(verbose_name='published')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('body', models.TextField(verbose_name='body')),
                ('is_public', models.BooleanField(default=True)),
                ('added', models.DateField(auto_now_add=True, verbose_name='added')),
                ('modified', models.DateField(auto_now=True, verbose_name='modified')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_image', to='photologue.Photo')),
            ],
            options={
                'ordering': ('-published',),
                'get_latest_by': 'published',
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
