# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='seo tags'),
        ),
    ]
